# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(465, 465)
        MainWindow.setStyleSheet("\n"
"background-color:   rgb(149, 218, 255);\n"
"Label_2 {\n"
"    \n"
"    font-size: 20px;\n"
"    color: #006325;     \n"
"}        ")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbltemprature = QtWidgets.QLabel(self.centralwidget)
        self.lbltemprature.setGeometry(QtCore.QRect(10, 80, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.lbltemprature.setFont(font)
        self.lbltemprature.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 0px; \n"
"color: rgb(255, 255, 255);\n"
"  border-radius: 20px;\n"
"    border-style: outset;\n"
"")
        self.lbltemprature.setObjectName("lbltemprature")
        self.pln = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.pln.setGeometry(QtCore.QRect(0, 0, 371, 81))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pln.setFont(font)
        self.pln.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.pln.setObjectName("pln")
        self.new_city = QtWidgets.QPushButton(self.centralwidget)
        self.new_city.setGeometry(QtCore.QRect(370, 0, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.new_city.setFont(font)
        self.new_city.setStyleSheet("QPushButton {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px  ;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(149, 218, 255, 255), stop:1 rgba(105, 216, 242, 237));\n"
"    padding: 1px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"  \n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(100, 201, 255, 255), stop:1 rgba(149, 218, 255, 255));\n"
"\n"
"\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:0, stop:0 rgba(120, 201, 255, 255), stop:0.473684 rgba(149, 218, 255, 255));\n"
"\n"
"\n"
"\n"
"    border-style: inset;\n"
"   \n"
"    }")
        self.new_city.setObjectName("new_city")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 141, 91))
        self.groupBox_2.setStyleSheet("background-color: rgb(119, 176, 204);\n"
"  border-radius: 20px;\n"
"    border-style: outset;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.latitude_label1_2 = QtWidgets.QLabel(self.groupBox_2)
        self.latitude_label1_2.setGeometry(QtCore.QRect(40, 10, 71, 30))
        self.latitude_label1_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.latitude_label1_2.setFont(font)
        self.latitude_label1_2.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.latitude_label1_2.setObjectName("latitude_label1_2")
        self.lbllat = QtWidgets.QLabel(self.groupBox_2)
        self.lbllat.setGeometry(QtCore.QRect(20, 40, 90, 50))
        self.lbllat.setMinimumSize(QtCore.QSize(90, 50))
        self.lbllat.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbllat.setFont(font)
        self.lbllat.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.lbllat.setText("")
        self.lbllat.setPixmap(QtGui.QPixmap(":/weather/icons/weather/png/031-weather forecast.png"))
        self.lbllat.setScaledContents(True)
        self.lbllat.setAlignment(QtCore.Qt.AlignCenter)
        self.lbllat.setObjectName("lbllat")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_6.setStyleSheet("background-color: rgb(119, 176, 204);")
        self.pushButton_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/lat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(160, 230, 141, 91))
        self.groupBox_3.setStyleSheet("background-color: rgb(119, 176, 204);\n"
"  border-radius: 20px;\n"
"    border-style: outset;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.latitude_label1_3 = QtWidgets.QLabel(self.groupBox_3)
        self.latitude_label1_3.setGeometry(QtCore.QRect(40, 10, 91, 30))
        self.latitude_label1_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.latitude_label1_3.setFont(font)
        self.latitude_label1_3.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.latitude_label1_3.setObjectName("latitude_label1_3")
        self.lblwinds = QtWidgets.QLabel(self.groupBox_3)
        self.lblwinds.setGeometry(QtCore.QRect(20, 40, 90, 50))
        self.lblwinds.setMinimumSize(QtCore.QSize(90, 50))
        self.lblwinds.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblwinds.setFont(font)
        self.lblwinds.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.lblwinds.setText("")
        self.lblwinds.setPixmap(QtGui.QPixmap(":/weather/icons/weather/png/031-weather forecast.png"))
        self.lblwinds.setScaledContents(True)
        self.lblwinds.setAlignment(QtCore.Qt.AlignCenter)
        self.lblwinds.setObjectName("lblwinds")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton.setStyleSheet("background-color: rgb(119, 176, 204);")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("image/wind2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(310, 230, 141, 91))
        self.groupBox_4.setStyleSheet("background-color: rgb(119, 176, 204);\n"
"  border-radius: 20px;\n"
"    border-style: outset;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.latitude_label1_4 = QtWidgets.QLabel(self.groupBox_4)
        self.latitude_label1_4.setGeometry(QtCore.QRect(40, 10, 41, 30))
        self.latitude_label1_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.latitude_label1_4.setFont(font)
        self.latitude_label1_4.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.latitude_label1_4.setObjectName("latitude_label1_4")
        self.lbltemp = QtWidgets.QLabel(self.groupBox_4)
        self.lbltemp.setGeometry(QtCore.QRect(20, 40, 90, 50))
        self.lbltemp.setMinimumSize(QtCore.QSize(90, 50))
        self.lbltemp.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbltemp.setFont(font)
        self.lbltemp.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.lbltemp.setText("")
        self.lbltemp.setPixmap(QtGui.QPixmap(":/weather/icons/weather/png/031-weather forecast.png"))
        self.lbltemp.setScaledContents(True)
        self.lbltemp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbltemp.setObjectName("lbltemp")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(119, 176, 204);")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image/temp3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 340, 141, 91))
        self.groupBox_5.setStyleSheet("background-color: rgb(119, 176, 204);\n"
"  border-radius: 20px;\n"
"    border-style: outset;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.latitude_label1_5 = QtWidgets.QLabel(self.groupBox_5)
        self.latitude_label1_5.setGeometry(QtCore.QRect(40, 10, 71, 30))
        self.latitude_label1_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.latitude_label1_5.setFont(font)
        self.latitude_label1_5.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.latitude_label1_5.setObjectName("latitude_label1_5")
        self.lbllot = QtWidgets.QLabel(self.groupBox_5)
        self.lbllot.setGeometry(QtCore.QRect(20, 40, 90, 50))
        self.lbllot.setMinimumSize(QtCore.QSize(90, 50))
        self.lbllot.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbllot.setFont(font)
        self.lbllot.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.lbllot.setText("")
        self.lbllot.setPixmap(QtGui.QPixmap(":/weather/icons/weather/png/031-weather forecast.png"))
        self.lbllot.setScaledContents(True)
        self.lbllot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbllot.setObjectName("lbllot")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_3.setStyleSheet("background-color: rgb(119, 176, 204);")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("image/lat2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(160, 340, 141, 91))
        self.groupBox_6.setStyleSheet("background-color: rgb(119, 176, 204);\n"
"  border-radius: 20px;\n"
"    border-style: outset;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.latitude_label1_6 = QtWidgets.QLabel(self.groupBox_6)
        self.latitude_label1_6.setGeometry(QtCore.QRect(50, 10, 61, 30))
        self.latitude_label1_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.latitude_label1_6.setFont(font)
        self.latitude_label1_6.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.latitude_label1_6.setObjectName("latitude_label1_6")
        self.lblsunrise = QtWidgets.QLabel(self.groupBox_6)
        self.lblsunrise.setGeometry(QtCore.QRect(20, 40, 90, 50))
        self.lblsunrise.setMinimumSize(QtCore.QSize(90, 0))
        self.lblsunrise.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblsunrise.setFont(font)
        self.lblsunrise.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.lblsunrise.setText("")
        self.lblsunrise.setPixmap(QtGui.QPixmap(":/weather/icons/weather/png/031-weather forecast.png"))
        self.lblsunrise.setScaledContents(True)
        self.lblsunrise.setAlignment(QtCore.Qt.AlignCenter)
        self.lblsunrise.setObjectName("lblsunrise")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_4.setStyleSheet("background-color: rgb(119, 176, 204);")
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("image/sunrise.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(310, 340, 141, 91))
        self.groupBox_7.setStyleSheet("background-color: rgb(119, 176, 204);\n"
"  border-radius: 20px;\n"
"    border-style: outset;")
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.latitude_label1_7 = QtWidgets.QLabel(self.groupBox_7)
        self.latitude_label1_7.setGeometry(QtCore.QRect(40, 10, 71, 30))
        self.latitude_label1_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        self.latitude_label1_7.setFont(font)
        self.latitude_label1_7.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.latitude_label1_7.setObjectName("latitude_label1_7")
        self.lblpressure = QtWidgets.QLabel(self.groupBox_7)
        self.lblpressure.setGeometry(QtCore.QRect(20, 40, 90, 50))
        self.lblpressure.setMinimumSize(QtCore.QSize(90, 50))
        self.lblpressure.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblpressure.setFont(font)
        self.lblpressure.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 2px; \n"
"color: rgb(255, 255, 255);")
        self.lblpressure.setText("")
        self.lblpressure.setPixmap(QtGui.QPixmap(":/weather/icons/weather/png/031-weather forecast.png"))
        self.lblpressure.setScaledContents(True)
        self.lblpressure.setAlignment(QtCore.Qt.AlignCenter)
        self.lblpressure.setObjectName("lblpressure")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.pushButton_5.setStyleSheet("background-color: rgb(119, 176, 204);")
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("image/pressure.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.mintemp = QtWidgets.QLabel(self.centralwidget)
        self.mintemp.setGeometry(QtCore.QRect(280, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mintemp.setFont(font)
        self.mintemp.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 0px; \n"
"color: rgb(255, 255, 255);\n"
"  border-radius: 20px;\n"
"    border-style: outset;\n"
"")
        self.mintemp.setObjectName("mintemp")
        self.maxtemp = QtWidgets.QLabel(self.centralwidget)
        self.maxtemp.setGeometry(QtCore.QRect(360, 130, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxtemp.setFont(font)
        self.maxtemp.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 0px; \n"
"color: rgb(255, 255, 255);\n"
"  border-radius: 20px;\n"
"    border-style: outset;\n"
"")
        self.maxtemp.setObjectName("maxtemp")
        self.status = QtWidgets.QLabel(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(280, 80, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.status.setFont(font)
        self.status.setStyleSheet("border-color:rgb(149, 218, 255);\n"
"border: 0px; \n"
"color: rgb(255, 255, 255);\n"
"  border-radius: 20px;\n"
"    border-style: outset;\n"
"")
        self.status.setObjectName("status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbltemprature.setText(_translate("MainWindow", "6"))
        self.pln.setPlainText(_translate("MainWindow", "Location"))
        self.new_city.setText(_translate("MainWindow", "weather"))
        self.latitude_label1_2.setText(_translate("MainWindow", "Latitude"))
        self.latitude_label1_3.setText(_translate("MainWindow", "wind speed"))
        self.latitude_label1_4.setText(_translate("MainWindow", "temp"))
        self.latitude_label1_5.setText(_translate("MainWindow", "Longitude"))
        self.latitude_label1_6.setText(_translate("MainWindow", "sunrise"))
        self.latitude_label1_7.setText(_translate("MainWindow", "pressure"))
        self.mintemp.setText(_translate("MainWindow", "mintemp"))
        self.maxtemp.setText(_translate("MainWindow", "maxtemp"))
        self.status.setText(_translate("MainWindow", "clouds"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
